# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
    inputs:
      useMinimalInputSet:
        required: true
        type: boolean
        default: true

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # - name: Restore dependencies
    #   working-directory: ./Generator/
    #   run: dotnet restore
    
    # - name: Build
    #   working-directory: ./Generator/
    #   run: dotnet build --no-restore

    - name: Set up
      if: ${{ inputs.useMinimalInputSet }}
      working-directory: ./Scripts/
      shell: bash
      run: ./bootstrap-localDev.sh
    
    - name: Generate Minimal Site
      if: ${{ inputs.useMinimalInputSet }}
      working-directory: ./Generator/
      run: dotnet run --configuration Release -- deploy

    - name: Generate Full Site
      if: ${{ !inputs.useMinimalInputSet }}
      working-directory: ./Generator/
      env:
        DEPLOYMENT_ENVIRONMENT: PROD
      run: dotnet run --configuration Release -- deploy

    - name: Deploy to Netlify
      id: deploy_to_netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './_site'
        deploy-message: ${{ github.head_ref }}
        production-deploy: ${{ !inputs.useMinimalInputSet && github.ref == 'refs/heads/master' }}
        alias: ${{ github.ref == 'refs/heads/master' && '' || github.head_ref }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Comment on PR
      if: ${{ env.PR_NUMBER != '' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: process.env.PR_NUMBER,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployed to ${{ steps.deploy_to_netlify.outputs.deploy-url }}'
          })
